# Checks for occurances of DEVELOPMENT_TEAM ID
name: Check-IDs

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Check_Development_Team_ID:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Check if DEVELOPMENT_TEAM ID exists
      - name: Scan project.pbxproj
        run: |
          cd Informant.xcodeproj/
          ls
          if grep -q "DEVELOPMENT_TEAM = \"\"" project.pbxproj; then
            echo ✅ No Development Team ID found!
            exit 0
          elif grep -q "DEVELOPMENT_TEAM = [a-zA-Z0-9]\+\;" project.pbxproj; then
            echo ERROR: ⛔️ Development Team ID found. Please remove this.
            exit 1
          else
            echo 🧀 Development Team ID field not found!
            exit 1
          fi
